version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: farm-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"   # host:container (you connect on localhost:5433)
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"   # access pgAdmin at http://localhost:8080
    depends_on:
      - db

volumes:
  db_data:
