version: "3.8"
services:
  db:
    image: pgvector/pgvector:pg17   # image with pgvector enabled
    environment:
      POSTGRES_DB: embeddings_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
